version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongodb_docker
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  mongo_express:
    image: mongo-express
    container_name: mongo-express_docker
    restart: always
    depends_on:
      - mongo
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo

  backend:
    container_name: nest-backend
    build:
      context: ./anshuldoc95/project-vm-cicd-nest-ayegree:1.0.1
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
    ports:
      - "${NEST_PORT}:${NEST_PORT}"
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}
    volumes:
      - ./anshuldoc95/project-vm-cicd-nest-ayegree:/app
    working_dir: /app
    command: npm run start:prod

volumes:
  mongo-data:
